services:
  gerador_placas_php:
    container_name: gerador_placas_php
    build:
      context: "./.docker"
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - APP_PORT=9001
    volumes:
      - "./.:/var/www/html"